class Matricula:
    def __init__(self,id,nombre,curso):
        self.__id=id
        self.nombre=nombre
        self.curso=curso
    def darnombre(self):
        return self.__id,self.nombre,self.curso
class Maestro:
    def __init__(self,nombre,apellido,id_maestro,usuario,contraseña):
        self
        
class menu:
    def __init__(self):
        self
on=Matricula(input("id\n"),input("nombre\n"),input("curso\n"))
print(on.darnombre())
